### ISSUE TITLE
First Tap on Sample left button shows square button

### ISSUE THREAD

**Issue by mcstoufer** [enmiller/ENMBadgedBarButtonItem#9]
Later taps re-render properly as rounded button.

This occurs at least on iOS 9.2, both device & simulator.

I'm still working on a possible fix for this.

**Comment by mcstoufer** [comment]
Updating this method looks to fix it.
```
- (void)setBadgeValue:(NSString *)badgeValue {
    _badgeValue = badgeValue;
    
    if ([self shouldBadgeHide:badgeValue]) {
        [self removeBadge];
        return;
    }
    
    if (self.badgeLabel) {
        [self updateBadgeValueAnimated:YES];
    } else {
        self.badgeLabel = [self newBadgeLabel];
        [self updateBadgeProperties];
        [self.customView addSubview:self.badgeLabel];

        // Pull the setting of the value and layer border radius off onto the next event loop.
        dispatch_async(dispatch_get_main_queue(), ^{
            self.badgeLabel.text = self.badgeValue;
            [self updateBadgeFrame];
        });
    }
}
```

**Comment by enmiller** [comment]
@mcstoufer I can try and look at this over the weekend and report back to you.

**Comment by enmiller** [comment]
@mcstoufer Looks good

**Comment by mcstoufer** [comment]
Glad I could help out. We are quite pleased with the functionality. I tweaked some internal settings to adjust the alignment of the button over the image. Probably not worth providing those changes?

**Comment by enmiller** [comment]
@mcstoufer Feel free to submit a PR for anything and I'll take a look at it.  I did this fairly hastily for a prototype a few years ago so I'm glad its helping out the community.
